### ISSUE TITLE
Fails to compile on RHEL7 little endian ppc64le

### ISSUE THREAD

**Issue by kaustubh-d** [ffi/ffi#413]
Fails to compile on RHEL7 little endian ppc64le. Has anybody tried and got it working on this platform?

First failure is 
Configuring libffi
/home/jenkins/kaustubh/thirdparty/kdffi/ffi/ext/ffi_c/libffi/config.guess: unable to guess system type
...
This platform guess is overcome by using the latest config.guess
http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD

Next issue is:
libtool: link: gcc -shared  -fPIC -DPIC  src/.libs/debug.o src/.libs/prep_cif.o src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o src/.libs/closures.o src/powerpc/.libs/ffi.o src/powerpc/.libs/sysv.o src/powerpc/.libs/ppc_closure.o src/powerpc/.libs/linux64.o src/powerpc/.libs/linux64_closure.o      -Wl,-soname -Wl,libffi.so.5 -o .libs/libffi.so.5.0.10
/usr/bin/ld: src/powerpc/.libs/linux64.o: ABI version 1 is not compatible with ABI version 2 output
/

Again if I pull in latest libffi source code, am able to get it compile with some tweaks, but ffi gem tests would fails for ./spec/ffi/variadic_spec.rb, example
  595) Function with variadic arguments call(dfj, double,9.87654321,float,1.23456789,long_long,2211230779876286898)
     Failure/Error: expect(p.get_float64(off)).to eq(v)

```
   expected: 9.87654321
        got: 3.4766470625842e-310
```

 Seems extension code will need some porting to work with latest libffi source code.

Same issues for Ubuntu 14 LE on ppc64le

**Comment by kaustubh-d** [comment]
Any inputs on this?

**Comment by tduehr** [comment]
These platforms are supported on a "this *should* work" basis.

That said, we're working on getting a process together for building VMs for all the supported platforms to enable actual testing across the board.

If you update libffi (either in the repo or by installing libffi-devel) does that correct the problem?

Do the ffi tests pass under jruby?

**Comment by mattray** [comment]
I talked with IBM about the issue and they pointed to this commit back in August that was merged to master:
https://github.com/ffi/ffi/commit/30f155d05cac28d82baf0283404b675222616f9d

but if you look in the latest gem release 1.9.6, that patch isn't in there. Was 1.9.6 not built from master?

**Comment by kaustubh-d** [comment]
Yes, and this is what works
- get latest libffi 3.2.1 built and installed on the system
- ensure pkg-config is able to detect libffi, else set the PKG_CONFIG_PATH path (example PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/)
- ruby ffi gem builds successfully and tests are also green (since it uses the system installed libffi and not the internal)

**Comment by tduehr** [comment]
Was this fixed in 1.9.8?

**Comment by kaustubh-d** [comment]
Thanks @tduehr  for releasing 1.9.8. It has the fix for Variadic tests. 

Still we will have to update the embedded ext/ffi_c/libffi to version 3.2.1 as the current gem successfully installs only if you have libffi 3.2.1 built and installed on the ppc64le system.

Have raised a PR to update libffi source to 3.2.1 so one does not have to rely on system installed libffi. https://github.com/ffi/ffi/pull/424

**Comment by SriramaSharma** [comment]
On RHEL 7.1 LE & Ubuntu 14.04 & 14.10, "gem install ffi" still fails to build with ffi 1.9.8 using the embedded libffi extension source. 
Given that bug #424 which was opened to update libffi 3.2.1 is now closed (as it requires more work than just updating). Is it acceptable to just update config.guess and config.sub in currently embedded 3.0.10 sources itself to ensure the build goes through successfully on ppc64le architecture.

**Comment by tduehr** [comment]
Is libffi-devel not available on ppcle64? Are the changes you need already in the upstream library?

**Comment by kaustubh-d** [comment]
I think libffi-devel may not be available. you should install libffi 3.2.1
from source and use
PKG_CONFIG_PATH='/usr/local/lib/pkgconfig/' gem install ffi
Basically set this path to where libffi.pc can be found after install from
source.

**Comment by SriramaSharma** [comment]
libffi-devel packages are available on ppc64le (both Ubuntu and RHEL 7.1 LE) and if we install the same from the distro, the gem install works fine. However gem should be installable with the embedded libffi version as well. 
As validated by @kaustubh-d (v in the above comment, the updated version of libffi (v3.2.1) does include all changes required to get built on ppc64le.

**Comment by tduehr** [comment]
getting working VMs has been taking longer than expected. I think I have a general process now but I haven't had time to test it.

**Comment by tduehr** [comment]
Any of you able to help get a vm up and running? I'm trying to debootstrap a ppc64el rootfs from an x86_64 VMWare VM. I'm stuck at the second stage with:

```
/sbin/ldconfig.real: 1: /sbin/ldconfig.real: Syntax error: "(" unexpected
```

**Comment by SriramaSharma** [comment]
@tduehr - Here is short URL which has details on how to get Linus on Power Hardware Access: https://ibm.biz/LoP_Access
On PDP, Usually one should be able to get the VM orchestrated within 2-3 hrs from the time request is made.

**Comment by tduehr** [comment]
Thanks I'll keep that in mind. I'd still like a local VM (or actual hardware).

**Comment by ramereth** [comment]
@tduehr We have a [POWER8 openstack](http://osuosl.org/services/powerdev) cluster you can use to spin up a VM to figure out the issue. Feel free to fill out the form and I'll make sure we get your acces setup rather quickly.

**Comment by ramereth** [comment]
And just to be clear, these are VMs running on actual POWER8 hardware virtualized using KVM. I actually ran into this problem on a VM running on this platform (which is why I'm watching this issue).

**Comment by troypete** [comment]
@tduehr IBM posted a $200 Bounty as an incentive to get this closed --> https://www.bountysource.com/issues/9099808-fails-to-compile-on-rhel7-little-endian-ppc64le

**Comment by tduehr** [comment]
you using ruby installed via yum/apt or rvm?

**Comment by SriramaSharma** [comment]
@tduehr  Yes, I am using ruby that is part of the distro and installed using yum/apt on RHEL 7.1 LE & Ubuntu 14.04 respectively.

On RHEL 7.1 LE: 
    $ ruby -v
    ruby 2.0.0p598 (2014-11-13) [powerpc64le-linux]
    [u0011847@sys-71809 ~]$ rpm -qa | grep rubygems
    rubygems-devel-2.0.14-24.ael7b.noarch
    rubygems-2.0.14-24.ael7b.noarch

On Ubuntu:
    $ ruby -v
    ruby 2.1.2p95 (2014-05-08) [powerpc64le-linux-gnu]

**Comment by SriramaSharma** [comment]
@tduehr, were you able to get access to the Power server to test the newer version of libffi ? please let know if you need any further info.

**Comment by SriramaSharma** [comment]
@tduehr FYI, IBM has now bumped the bounty amount to $500 encouraging quick closure of this issue -> https://www.bountysource.com/issues/9099808-fails-to-compile-on-rhel7-little-endian-ppc64le
Please let know if you need any help in getting access to server to get the testing done.

**Comment by daxtens** [comment]
This is (as I understand it) addressed in @ruscur pull request #484.
