### ISSUE TITLE
ERROR: Failed to build gem native extension. win 7 64

### ISSUE THREAD

**Issue by eltjootje** [ffi/ffi#445]
My maven build that uses rubygems:compass  failed over night.

Here is the error message.
     [exec] [WARNING] ERROR:  Error installing C:\Users\xxxx\.m2\repository\rubygems\ffi\1.9.10\ffi-1.9.10.gem:
     [exec] [WARNING]   ERROR: Failed to build gem native extension.
     [exec] [WARNING]
     [exec] [WARNING]     java -jar /C:/Users/xxxx/.m2/repository/org/jruby/jruby-complete/1.7.6/jruby-complete-1.7.6.jar extconf.rb
     [exec] [WARNING] Error: Unable to access jarfile /C:/Users/xxxx/.m2/repository/org/jruby/jruby-complete/1.7.6/jruby-complete-1.7.6.jar
     [exec] [WARNING]
     [exec] [WARNING]
     [exec] [WARNING] Gem files will remain installed in C:/Users/xxxx/temp/dev/rubygems/gems/ffi-1.9.10 for inspection.
     [exec] [WARNING] Results logged to C:/Users/xxxx/temp/dev/rubygems/gems/ffi-1.9.10/ext/ffi_c/gem_make.out

Contents of the gem_make.out file:
java -jar /C:/Users/xxxx/.m2/repository/org/jruby/jruby-complete/1.7.6/jruby-complete-1.7.6.jar extconf.rb
Error: Unable to access jarfile /C:/Users/xxxx/.m2/repository/org/jruby/jruby-complete/1.7.6/jruby-complete-1.7.6.jar

Looks like an incorrect path:  '...jarfile /C:/Users/xxxx...'
Any suggestion how to fix this or work around it?

Thanks,
  Eltjo.

**Comment by larskanis** [comment]
This is because the java specific gem in not yet pushed to rubygems.org.

@tduehr Java and windows binary gems of 1.9.10 are missing on rubygems.org. This is especially interesting because #441 is specific to the Windows platform. I have the gems ready to push and still have push rights - so if you're too busy, give me a sign to do so.

**Comment by larskanis** [comment]
I pushed the ffi-1.9.10-java.gem to rubygems.org. Does this fix your issue?

**Comment by eltjootje** [comment]
It still doesn't work. The same errors. Should I do something to make sure your version is used?
Thanks a lot for your help,
  Eltjo.

**Comment by tduehr** [comment]
`gem install ffi --platform java`

also try clearing your maven cache. It looks like it's trying to use an outdated jruby-complete from your local maven repo. Please post a new copy of the logs.

**Comment by tduehr** [comment]
Did the push of 1.9.10-java solve this?

**Comment by tduehr** [comment]
no comment in two months, closing.
