### ISSUE TITLE
Fails to build on 10.14.5

### ISSUE THREAD

**Issue by jjb** [ffi/ffi#705]
Let me know if you need any more info

```
➔ ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
➔ type ruby
ruby is /opt/local/bin/ruby
➔ uname -a
Darwin Johns-MacBook-Pro.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
➔ xcode-select --install      
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

```
➔ sudo gem install ffi
Password:
Building native extensions. This could take a while...
ERROR:  Error installing ffi:
	ERROR: Failed to build gem native extension.

    current directory: /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c
/opt/local/bin/ruby2.6 -I /opt/local/lib/ruby2.6/2.6.0 -r ./siteconf20190603-19467-xkq7xk.rb extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... no
checking for shlwapi.h... no
checking for rb_thread_call_without_gvl()... yes
checking for ruby_native_thread_p()... yes
checking for ruby_thread_has_gvl_p()... yes
creating extconf.h
creating Makefile

current directory: /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c
make "DESTDIR=" clean

current directory: /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c
make "DESTDIR="
mkdir -p "/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c"/libffi-x86_64; (if [ ! -f "/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi"/configure ]; then echo "Running autoreconf for libffi"; cd "/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi" && /bin/sh /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/autogen.sh > /dev/null; fi); (if [ ! -f "/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c"/libffi-x86_64/Makefile ]; then echo "Configuring libffi for x86_64"; cd "/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c"/libffi-x86_64 && env CC=" /usr/bin/clang" CFLAGS="-arch x86_64 " LDFLAGS="-arch x86_64" "/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi"/configure --disable-static --with-pic=yes --disable-dependency-tracking --disable-docs --host=x86_64-apple-darwin > /dev/null; fi); env MACOSX_DEPLOYMENT_TARGET=10.4 /Applications/Xcode.app/Contents/Developer/usr/bin/make -C "/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c"/libffi-x86_64
Configuring libffi for x86_64
clang: error: unsupported option '-print-multi-os-directory'
clang: error: no input files
/Applications/Xcode.app/Contents/Developer/usr/bin/make 'AR_FLAGS=' 'CC_FOR_BUILD=' 'CFLAGS=-arch x86_64  -Wall -fexceptions' 'CXXFLAGS=-g -O2' 'CFLAGS_FOR_BUILD=' 'CFLAGS_FOR_TARGET=' 'INSTALL=/usr/bin/install -c' 'INSTALL_DATA=/usr/bin/install -c -m 644' 'INSTALL_PROGRAM=/usr/bin/install -c' 'INSTALL_SCRIPT=/usr/bin/install -c' 'JC1FLAGS=' 'LDFLAGS=-arch x86_64' 'LIBCFLAGS=' 'LIBCFLAGS_FOR_TARGET=' 'MAKE=/Applications/Xcode.app/Contents/Developer/usr/bin/make' 'MAKEINFO=/bin/sh /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/missing makeinfo ' 'PICFLAG=' 'PICFLAG_FOR_TARGET=' 'RUNTESTFLAGS=' 'SHELL=/bin/sh' 'exec_prefix=/usr/local' 'infodir=/usr/local/share/info' 'libdir=/usr/local/lib' 'mandir=/usr/local/share/man' 'prefix=/usr/local' 'AR=ar' 'AS=as' 'CC=/usr/bin/clang' 'CXX=g++' 'LD=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld' 'NM=nm' 'RANLIB=ranlib' 'DESTDIR=' all-recursive
Making all in include
make[3]: Nothing to be done for `all'.
Making all in testsuite
make[3]: Nothing to be done for `all'.
Making all in man
make[3]: Nothing to be done for `all'.
/bin/sh ./libtool  --tag=CC   --mode=compile /usr/bin/clang -DHAVE_CONFIG_H -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi  -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src   -arch x86_64  -Wall -fexceptions -c -o src/prep_cif.lo /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/prep_cif.c
libtool: compile:  /usr/bin/clang -DHAVE_CONFIG_H -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -arch x86_64 -Wall -fexceptions -c /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/prep_cif.c  -fno-common -DPIC -o src/.libs/prep_cif.o
/bin/sh ./libtool  --tag=CC   --mode=compile /usr/bin/clang -DHAVE_CONFIG_H -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi  -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src   -arch x86_64  -Wall -fexceptions -c -o src/types.lo /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/types.c
libtool: compile:  /usr/bin/clang -DHAVE_CONFIG_H -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -arch x86_64 -Wall -fexceptions -c /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/types.c  -fno-common -DPIC -o src/.libs/types.o
/bin/sh ./libtool  --tag=CC   --mode=compile /usr/bin/clang -DHAVE_CONFIG_H -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi  -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src   -arch x86_64  -Wall -fexceptions -c -o src/raw_api.lo /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/raw_api.c
libtool: compile:  /usr/bin/clang -DHAVE_CONFIG_H -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -arch x86_64 -Wall -fexceptions -c /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/raw_api.c  -fno-common -DPIC -o src/.libs/raw_api.o
/bin/sh ./libtool  --tag=CC   --mode=compile /usr/bin/clang -DHAVE_CONFIG_H -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi  -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src   -arch x86_64  -Wall -fexceptions -c -o src/java_raw_api.lo /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/java_raw_api.c
libtool: compile:  /usr/bin/clang -DHAVE_CONFIG_H -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -arch x86_64 -Wall -fexceptions -c /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/java_raw_api.c  -fno-common -DPIC -o src/.libs/java_raw_api.o
/bin/sh ./libtool  --tag=CC   --mode=compile /usr/bin/clang -DHAVE_CONFIG_H -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi  -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src   -arch x86_64  -Wall -fexceptions -c -o src/closures.lo /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/closures.c
libtool: compile:  /usr/bin/clang -DHAVE_CONFIG_H -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -arch x86_64 -Wall -fexceptions -c /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/closures.c  -fno-common -DPIC -o src/.libs/closures.o
/bin/sh ./libtool  --tag=CC   --mode=compile /usr/bin/clang -DHAVE_CONFIG_H -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi  -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src   -arch x86_64  -Wall -fexceptions -c -o src/x86/ffi64.lo /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/x86/ffi64.c
libtool: compile:  /usr/bin/clang -DHAVE_CONFIG_H -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -arch x86_64 -Wall -fexceptions -c /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/x86/ffi64.c  -fno-common -DPIC -o src/x86/.libs/ffi64.o
/bin/sh ./libtool    --mode=compile /usr/bin/clang -DHAVE_CONFIG_H -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi  -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src  -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -arch x86_64  -c -o src/x86/unix64.lo /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/x86/unix64.S
libtool: compile:  /usr/bin/clang -DHAVE_CONFIG_H -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -arch x86_64 -c /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/x86/unix64.S  -fno-common -DPIC -o src/x86/.libs/unix64.o
/bin/sh ./libtool  --tag=CC   --mode=compile /usr/bin/clang -DHAVE_CONFIG_H -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi  -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src   -arch x86_64  -Wall -fexceptions -c -o src/x86/ffiw64.lo /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/x86/ffiw64.c
libtool: compile:  /usr/bin/clang -DHAVE_CONFIG_H -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -arch x86_64 -Wall -fexceptions -c /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/x86/ffiw64.c  -fno-common -DPIC -o src/x86/.libs/ffiw64.o
/bin/sh ./libtool    --mode=compile /usr/bin/clang -DHAVE_CONFIG_H -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi  -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src  -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -arch x86_64  -c -o src/x86/win64.lo /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/x86/win64.S
libtool: compile:  /usr/bin/clang -DHAVE_CONFIG_H -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -I. -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -arch x86_64 -c /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/x86/win64.S  -fno-common -DPIC -o src/x86/.libs/win64.o
/bin/sh ./libtool  --tag=CC   --mode=link /usr/bin/clang  -arch x86_64  -Wall -fexceptions  -arch x86_64 -o libffi_convenience.la  src/prep_cif.lo src/types.lo src/raw_api.lo src/java_raw_api.lo src/closures.lo   src/x86/ffi64.lo src/x86/unix64.lo src/x86/ffiw64.lo src/x86/win64.lo 
libtool: link: ar cru .libs/libffi_convenience.a src/.libs/prep_cif.o src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o src/.libs/closures.o src/x86/.libs/ffi64.o src/x86/.libs/unix64.o src/x86/.libs/ffiw64.o src/x86/.libs/win64.o 
libtool: link: ranlib .libs/libffi_convenience.a
libtool: link: ( cd ".libs" && rm -f "libffi_convenience.la" && ln -s "../libffi_convenience.la" "libffi_convenience.la" )
/bin/sh ./libtool  --tag=CC   --mode=link /usr/bin/clang  -arch x86_64  -Wall -fexceptions -no-undefined -version-info `grep -v '^#' /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c/libffi/libtool-version`   '-arch' 'x86_64'  -arch x86_64 -o libffi.la -rpath /usr/local/lib src/prep_cif.lo src/types.lo src/raw_api.lo src/java_raw_api.lo src/closures.lo  src/x86/ffi64.lo src/x86/unix64.lo src/x86/ffiw64.lo src/x86/win64.lo 
libtool: link:  /usr/bin/clang -dynamiclib  -o .libs/libffi.7.dylib  src/.libs/prep_cif.o src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o src/.libs/closures.o src/x86/.libs/ffi64.o src/x86/.libs/unix64.o src/x86/.libs/ffiw64.o src/x86/.libs/win64.o    -arch x86_64 -arch x86_64 -arch x86_64   -install_name  /usr/local/lib/libffi.7.dylib -compatibility_version 9 -current_version 9.0 -Wl,-single_module
ld: library not found for -lgcc_s.10.4
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libffi.la] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** ["/opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1/ext/ffi_c"/libffi-x86_64/.libs/libffi_convenience.a] Error 2

make failed, exit code 2

Gem files will remain installed in /opt/local/lib/ruby2.6/gems/2.6.0/gems/ffi-1.11.1 for inspection.
Results logged to /opt/local/lib/ruby2.6/gems/2.6.0/extensions/x86_64-darwin-18/2.6.0/ffi-1.11.1/gem_make.out
```

**Comment by MtnBiker** [comment]
Similar here with chruby and Mojave. Also tried `gem install ffi -v '1.11.1' --source 'https://rubygems.org/'`

    chruby
       ruby-2.5.1
       ruby-2.6.1
     * ruby-2.6.2

    ~ 
    ➜ gem install ffi
    Building native extensions. This could take a while...
    ERROR:  Error installing ffi:
    	ERROR: Failed to build gem native extension.

        current directory: /Users/me/.gem/ruby/2.6.2/gems/ffi-1.11.1/ext/ffi_c
    /Users/me/.rubies/ruby-2.6.2/bin/ruby -I /Users/me/.rubies/ruby-2.6.2/lib/ruby/2.6.0 -r ./siteconf20190615-41822-ia9ttb.rb extconf.rb
    checking for ffi.h... no
    checking for ffi.h in /usr/local/include,/usr/include/ffi... no
    checking for shlwapi.h... no
    checking for rb_thread_call_without_gvl()... yes
    checking for ruby_native_thread_p()... yes
    checking for ruby_thread_has_gvl_p()... yes
    creating extconf.h
    creating Makefile

    current directory: /Users/me/.gem/ruby/2.6.2/gems/ffi-1.11.1/ext/ffi_c
    make "DESTDIR=" clean

    current directory: /Users/me/.gem/ruby/2.6.2/gems/ffi-1.11.1/ext/ffi_c
    make "DESTDIR="
    Configuring libffi
    clang: error: unsupported option '-print-multi-os-directory'
    clang: error: no input files
    cd "/Users/me/.gem/ruby/2.6.2/gems/ffi-1.11.1/ext/ffi_c/libffi-x86_64-darwin18" && /Volumes/Seagate 8TB Backup/Xcode.app/Contents/Developer/usr/bin/make
    /bin/sh: /Volumes/Seagate: No such file or directory
    make: *** ["/Users/me/.gem/ruby/2.6.2/gems/ffi-1.11.1/ext/ffi_c/libffi-x86_64-darwin18"/.libs/libffi_convenience.a] Error 127

    make failed, exit code 2

    Gem files will remain installed in /Users/me/.gem/ruby/2.6.2/gems/ffi-1.11.1 for inspection.
    Results logged to /Users/me/.gem/ruby/2.6.2/extensions/x86_64-darwin-18/2.6.0-static/ffi-1.11.1/gem_make.out

**Comment by gthank** [comment]
Same issue as the original report (`ld: library not found for -lgcc_s.10.4`), on Ruby 2.4.7 from `rbenv` on macOS 10.14.6).

```
$  ruby --version                                                                                                                                                                        ruby 2.4.7p357 (2019-08-28 revision 67796) [x86_64-darwin18]

$ gcc --version                                                                                                                                                                         
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ gem install ffi

<here's the log>
current directory: /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c
/Users/hank/.rbenv/versions/2.4.7/bin/ruby -r ./siteconf20190910-6569-66l6wr.rb extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... no
checking for shlwapi.h... no
checking for rb_thread_call_without_gvl()... yes
checking for ruby_native_thread_p()... yes
checking for ruby_thread_has_gvl_p()... yes
creating extconf.h
creating Makefile

current directory: /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c
make "DESTDIR=" clean

current directory: /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c
make "DESTDIR="
mkdir -p "/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c"/libffi-x86_64; (if [ ! -f "/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi"/configure ]; then echo "Running autoreconf for libffi"; cd "/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi" && /bin/sh /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/autogen.sh > /dev/null; fi); (if [ ! -f "/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c"/libffi-x86_64/Makefile ]; then echo "Configuring libffi for x86_64"; cd "/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c"/libffi-x86_64 && env CC=" clang" CFLAGS="-arch x86_64 " LDFLAGS="-arch x86_64" "/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi"/configure --disable-static --with-pic=yes --disable-dependency-tracking --disable-docs --host=x86_64-apple-darwin > /dev/null; fi); env MACOSX_DEPLOYMENT_TARGET=10.4 /Applications/Xcode.app/Contents/Developer/usr/bin/make -C "/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c"/libffi-x86_64
Configuring libffi for x86_64
clang: error: unsupported option '-print-multi-os-directory'
clang: error: no input files
/Applications/Xcode.app/Contents/Developer/usr/bin/make 'AR_FLAGS=' 'CC_FOR_BUILD=' 'CFLAGS=-arch x86_64  -Wall -fexceptions' 'CXXFLAGS=-g -O2' 'CFLAGS_FOR_BUILD=' 'CFLAGS_FOR_TARGET=' 'INSTALL=/usr/bin/install -c' 'INSTALL_DATA=/usr/bin/install -c -m 644' 'INSTALL_PROGRAM=/usr/bin/install -c' 'INSTALL_SCRIPT=/usr/bin/install -c' 'JC1FLAGS=' 'LDFLAGS=-arch x86_64' 'LIBCFLAGS=' 'LIBCFLAGS_FOR_TARGET=' 'MAKE=/Applications/Xcode.app/Contents/Developer/usr/bin/make' 'MAKEINFO=/bin/sh /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/missing makeinfo ' 'PICFLAG=' 'PICFLAG_FOR_TARGET=' 'RUNTESTFLAGS=' 'SHELL=/bin/sh' 'exec_prefix=/usr/local' 'infodir=/usr/local/share/info' 'libdir=/usr/local/lib' 'mandir=/usr/local/share/man' 'prefix=/usr/local' 'AR=ar' 'AS=as' 'CC=clang' 'CXX=g++' 'LD=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld' 'NM=nm' 'RANLIB=ranlib' 'DESTDIR=' all-recursive
Making all in include
make[3]: Nothing to be done for `all'.
Making all in testsuite
make[3]: Nothing to be done for `all'.
Making all in man
make[3]: Nothing to be done for `all'.
/bin/sh ./libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi  -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -I/Users/hank/.rbenv/versions/2.4.7/include -I/usr/local/opt/mysql55/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -arch x86_64  -Wall -fexceptions -c -o src/prep_cif.lo /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/prep_cif.c
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -I/Users/hank/.rbenv/versions/2.4.7/include -I/usr/local/opt/mysql55/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT -arch x86_64 -Wall -fexceptions -c /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/prep_cif.c  -fno-common -DPIC -o src/.libs/prep_cif.o
/bin/sh ./libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi  -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -I/Users/hank/.rbenv/versions/2.4.7/include -I/usr/local/opt/mysql55/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -arch x86_64  -Wall -fexceptions -c -o src/types.lo /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/types.c
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -I/Users/hank/.rbenv/versions/2.4.7/include -I/usr/local/opt/mysql55/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT -arch x86_64 -Wall -fexceptions -c /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/types.c  -fno-common -DPIC -o src/.libs/types.o
/bin/sh ./libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi  -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -I/Users/hank/.rbenv/versions/2.4.7/include -I/usr/local/opt/mysql55/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -arch x86_64  -Wall -fexceptions -c -o src/raw_api.lo /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/raw_api.c
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -I/Users/hank/.rbenv/versions/2.4.7/include -I/usr/local/opt/mysql55/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT -arch x86_64 -Wall -fexceptions -c /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/raw_api.c  -fno-common -DPIC -o src/.libs/raw_api.o
/bin/sh ./libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi  -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -I/Users/hank/.rbenv/versions/2.4.7/include -I/usr/local/opt/mysql55/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -arch x86_64  -Wall -fexceptions -c -o src/java_raw_api.lo /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/java_raw_api.c
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -I/Users/hank/.rbenv/versions/2.4.7/include -I/usr/local/opt/mysql55/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT -arch x86_64 -Wall -fexceptions -c /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/java_raw_api.c  -fno-common -DPIC -o src/.libs/java_raw_api.o
/bin/sh ./libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi  -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -I/Users/hank/.rbenv/versions/2.4.7/include -I/usr/local/opt/mysql55/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -arch x86_64  -Wall -fexceptions -c -o src/closures.lo /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/closures.c
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -I/Users/hank/.rbenv/versions/2.4.7/include -I/usr/local/opt/mysql55/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT -arch x86_64 -Wall -fexceptions -c /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/closures.c  -fno-common -DPIC -o src/.libs/closures.o
/bin/sh ./libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi  -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -I/Users/hank/.rbenv/versions/2.4.7/include -I/usr/local/opt/mysql55/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -arch x86_64  -Wall -fexceptions -c -o src/x86/ffi64.lo /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/x86/ffi64.c
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -I/Users/hank/.rbenv/versions/2.4.7/include -I/usr/local/opt/mysql55/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT -arch x86_64 -Wall -fexceptions -c /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/x86/ffi64.c  -fno-common -DPIC -o src/x86/.libs/ffi64.o
/bin/sh ./libtool    --mode=compile clang -DHAVE_CONFIG_H -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi  -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -I/Users/hank/.rbenv/versions/2.4.7/include -I/usr/local/opt/mysql55/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -arch x86_64  -c -o src/x86/unix64.lo /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/x86/unix64.S
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -I/Users/hank/.rbenv/versions/2.4.7/include -I/usr/local/opt/mysql55/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -arch x86_64 -c /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/x86/unix64.S  -fno-common -DPIC -o src/x86/.libs/unix64.o
/bin/sh ./libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi  -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -I/Users/hank/.rbenv/versions/2.4.7/include -I/usr/local/opt/mysql55/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -arch x86_64  -Wall -fexceptions -c -o src/x86/ffiw64.lo /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/x86/ffiw64.c
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -I/Users/hank/.rbenv/versions/2.4.7/include -I/usr/local/opt/mysql55/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT -arch x86_64 -Wall -fexceptions -c /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/x86/ffiw64.c  -fno-common -DPIC -o src/x86/.libs/ffiw64.o
/bin/sh ./libtool    --mode=compile clang -DHAVE_CONFIG_H -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi  -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -I/Users/hank/.rbenv/versions/2.4.7/include -I/usr/local/opt/mysql55/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -arch x86_64  -c -o src/x86/win64.lo /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/x86/win64.S
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -DRUBY_EXTCONF_H=\"extconf.h\" -I/Users/hank/.rbenv/versions/2.4.7/include -I/usr/local/opt/mysql55/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT -I. -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/include -Iinclude -I/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src -arch x86_64 -c /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/src/x86/win64.S  -fno-common -DPIC -o src/x86/.libs/win64.o
/bin/sh ./libtool  --tag=CC   --mode=link clang  -arch x86_64  -Wall -fexceptions  -arch x86_64 -o libffi_convenience.la  src/prep_cif.lo src/types.lo src/raw_api.lo src/java_raw_api.lo src/closures.lo   src/x86/ffi64.lo src/x86/unix64.lo src/x86/ffiw64.lo src/x86/win64.lo 
libtool: link: ar cru .libs/libffi_convenience.a src/.libs/prep_cif.o src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o src/.libs/closures.o src/x86/.libs/ffi64.o src/x86/.libs/unix64.o src/x86/.libs/ffiw64.o src/x86/.libs/win64.o 
libtool: link: ranlib .libs/libffi_convenience.a
libtool: link: ( cd ".libs" && rm -f "libffi_convenience.la" && ln -s "../libffi_convenience.la" "libffi_convenience.la" )
/bin/sh ./libtool  --tag=CC   --mode=link clang  -arch x86_64  -Wall -fexceptions -no-undefined -version-info `grep -v '^#' /Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c/libffi/libtool-version`   '-arch' 'x86_64'  -arch x86_64 -o libffi.la -rpath /usr/local/lib src/prep_cif.lo src/types.lo src/raw_api.lo src/java_raw_api.lo src/closures.lo  src/x86/ffi64.lo src/x86/unix64.lo src/x86/ffiw64.lo src/x86/win64.lo 
libtool: link:  clang -dynamiclib  -o .libs/libffi.7.dylib  src/.libs/prep_cif.o src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o src/.libs/closures.o src/x86/.libs/ffi64.o src/x86/.libs/unix64.o src/x86/.libs/ffiw64.o src/x86/.libs/win64.o    -arch x86_64 -arch x86_64 -arch x86_64   -install_name  /usr/local/lib/libffi.7.dylib -compatibility_version 9 -current_version 9.0 -Wl,-single_module
ld: library not found for -lgcc_s.10.4
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libffi.la] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** ["/Users/hank/.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/ext/ffi_c"/libffi-x86_64/.libs/libffi_convenience.a] Error 2

make failed, exit code 2
```

**Comment by larskanis** [comment]
This issue should be fixed by ffi-1.11.2. Can you please verify?

**Comment by jjb** [comment]
still failing for me: https://gist.github.com/jjb/8c9d1b83360ad9676da1d6f863078b38
