### ISSUE TITLE
Missing compatible architecture for ARM64 builds

### ISSUE THREAD

**Issue by kellemar** [ffi/ffi#838]
Hi, I'm running this on a Macbook M1, and just got this error when running a pod install for one of my iOS projects.

missing compatible arch in /Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi_c.bundle - /Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi_c.bundle

Is there an updated version of ffi which has a bundle that supports ARM64?

**Comment by zhantx** [comment]
use `arch -x86_64 sudo gem install ffi`
and if you use cocoapods `arch -x86_64 pod install`

**Comment by sohooo** [comment]
> use `arch -x86_64 sudo gem install ffi`
> and if you use cocoapods `arch -x86_64 pod install`

This runs the process through Rosetta to emulate x86_64 arch. It works, but a native build would be an improvement.

**Comment by hartator** [comment]
Getting an error after `arch -x86_64 sudo gem install ffi` when running Rails, sass depends on ffi:

```
/Users/user/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': dlopen(/Users/user/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/ffi-1.12.2/lib/ffi_c.bundle, 9): Symbol not found: _ffi_type_double (LoadError)
  Referenced from: /Users/user/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/ffi-1.12.2/lib/ffi_c.bundle
  Expected in: flat namespace
 in /Users/user/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/ffi-1.12.2/lib/ffi_c.bundle - /Users/user/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/ffi-1.12.2/lib/ffi_c.bundle
```

**Comment by saschagehlich** [comment]
> use `arch -x86_64 sudo gem install ffi`

Please, don't install gems with sudo.

**Comment by larskanis** [comment]
Compatibility to arm64-darwin is fixed in ffi-1.14.0.

**Comment by awhitema6937121** [comment]
I am still seeing the arch missing error with 1.14.0

Installed with `gem install ffi --user-install`

`[iris:~]% cat test.rb 
#!/usr/bin/ruby

require 'ffi'

module Hello
  extend FFI::Library
  ffi_lib FFI::Library::LIBC
  attach_function :puts, [ :string ], :int
end

Hello.puts("Hello, World")
[iris:~]% ruby test.rb 
Traceback (most recent call last):
	2: from test.rb:3:in `<main>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ffi (LoadError)
	6: from test.rb:3:in `<main>'
	5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	2: from /Users/awhitema/.gem/ruby/2.6.0/gems/ffi-1.14.0/lib/ffi.rb:4:in `<top (required)>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- 2.6/ffi_c (LoadError)
	7: from test.rb:3:in `<main>'
	6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	3: from /Users/awhitema/.gem/ruby/2.6.0/gems/ffi-1.14.0/lib/ffi.rb:3:in `<top (required)>'
	2: from /Users/awhitema/.gem/ruby/2.6.0/gems/ffi-1.14.0/lib/ffi.rb:6:in `rescue in <top (required)>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Users/awhitema/.gem/ruby/2.6.0/gems/ffi-1.14.0/lib/ffi_c.bundle, 0x0009): missing compatible arch in /Users/awhitema/.gem/ruby/2.6.0/gems/ffi-1.14.0/lib/ffi_c.bundle - /Users/awhitema/.gem/ruby/2.6.0/gems/ffi-1.14.0/lib/ffi_c.bundle (LoadError)
zsh: exit 1     ruby test.rb
`
