### ISSUE TITLE
Missing file or directory for arm64-darwin workaround

### ISSUE THREAD

**Issue by bemky** [ffi/ffi#845]
I'm on an Apple M1 Mac Mini. Trying to get ffi running for middleman app. I added reference to github master in Gemfile to use latest version of master that has #843 (thanks @larskanis)
```ruby
# Gemfile
gem 'ffi', github: 'ffi/ffi'
gem 'middleman', '~> 4.2'
...
```

When running `bundle`, I get the following error:

```
current directory: /opt/homebrew/lib/ruby/gems/2.7.0/bundler/gems/ffi-7865f3f28ac6/ext/ffi_c
/opt/homebrew/opt/ruby/bin/ruby -I /opt/homebrew/Cellar/ruby/2.7.2/lib/ruby/2.7.0 -r ./siteconf20201125-1233-1bozv6z.rb extconf.rb
checking for ffi_prep_closure_loc() in -lffi... no
checking for ffi_prep_closure_loc() in -llibffi... no
checking for ffi_prep_closure_loc() in -llibffi-8... no
creating extconf.h
creating Makefile

current directory: /opt/homebrew/lib/ruby/gems/2.7.0/bundler/gems/ffi-7865f3f28ac6/ext/ffi_c
make "DESTDIR=" clean

current directory: /opt/homebrew/lib/ruby/gems/2.7.0/bundler/gems/ffi-7865f3f28ac6/ext/ffi_c
make "DESTDIR="
Running autoreconf for libffi
/bin/sh: /opt/homebrew/lib/ruby/gems/2.7.0/bundler/gems/ffi-7865f3f28ac6/ext/ffi_c/libffi/autogen.sh: No such file or directory
make: *** ["/opt/homebrew/lib/ruby/gems/2.7.0/bundler/gems/ffi-7865f3f28ac6/ext/ffi_c/libffi-arm64-darwin20"/.libs/libffi_convenience.a] Error 127

make failed, exit code 2
```

**Comment by nilleb** [comment]
I do not experience anymore this problem on 

```
Using ffi 1.13.1 from https://github.com/ffi/ffi.git (at master@d774198)
```

**Comment by nilleb** [comment]
.. But rather a 

```
/opt/homebrew/lib/ruby/gems/2.7.0/bundler/gems/ffi-d77419803ef9/lib/ffi/library.rb:275: [BUG] Bus Error at 0x00000001031ec000
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [arm64-darwin20]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:                    
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports.     

-- Control frame information -----------------------------------------------
c:0097 p:---- s:0555 e:000554 CFUNC  :attach
c:0096 p:0250 s:0549 e:000548 METHOD /opt/homebrew/lib/ruby/gems/2.7.0/bundler/gems/ffi-d77419803ef9/lib/ffi/library.rb:275
```
😭 

The crash report is here, just in case: [ruby_2020-12-01-211605_openarms.crash.zip](https://github.com/ffi/ffi/files/5625250/ruby_2020-12-01-211605_openarms.crash.zip)

**Comment by hcatlin** [comment]
Having the same issue as the original reporter with #d774198

**Comment by rgaufman** [comment]
Same issue here. Any update on this one?

**Comment by tdegrunt** [comment]
I ran into similar issues, perhaps this is helpful for someone:

Got this to work by: `brew install libtool automake autoconf`

Then `rake clean` & `rake compile`, once that was done, it started working.

**Comment by felixbuenemann** [comment]
I'm not seeing any crashes for sassc 2.0.1 with ffi master@a7f4c95 using either the bundled libffi 2.7.2 (`--disable-system-libffi`), macOS default (`--enable-system-libffi`) or Homebrew arm64 (`--with-ffi_c-dir=/opt/homebrew/opt/libffi`) on a 2020 M1 MacBook Air running macOS 11.1 (20C69) and Xcode / Xcode CLI 12.3.

If you want to use the bundled libffi make sure to add `submodules: true` to the gem line in the Gemfile.

**Comment by larskanis** [comment]
Compatibility to arm64-darwin is fixed in ffi-1.14.0.

**Comment by bemky** [comment]
Thanks @larskanis!

**Comment by RailsCod3rFuture** [comment]
Still an issue for ffi-1.15.0

/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/library.rb:275: [BUG] Bus Error at 0x00000....
